# 预备知识

#### Python基础(一些语法糖)

In [5]:
# 列表推导式(支持多层嵌套)
print([m + ' ' + n for m in ['ustc', 'nico'] for n in ['edu', 'com']]) 
# 带if选择的条件赋值
value = '666' if 2 > 1 else '444'
print(value)

# 匿名函数
print([(lambda x: x * x)(i) for i in range(10)])
# 用map函数实现, 需要调用list()函数转换为列表
print(list(map(lambda x: x * x, range(10))))

# zip函数将可迭代对象打包成元组, 通常用于循环
L1 = [1, 2, 3, 4]
L2 = ['a', 'b', 'c', 'd']
print(list(zip(L1, L2)))
# 解压操作zip(*)
print(list(zip(*zip(L1, L2))))
for (x, y) in zip(L1, L2):
    print(x, y)
# enumerate函数在迭代时绑定遍历序号, 通常用于循环
print('enumerate result:')
for index, value in enumerate(L2):
    print(index, value)
# 对两个列表建立字典映射时, 可以用zip函数
print(dict(zip(L1, L2)))

['ustc edu', 'ustc com', 'nico edu', 'nico com']
666
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]
[(1, 2, 3, 4), ('a', 'b', 'c', 'd')]
1 a
2 b
3 c
4 d
enumerate result:
0 a
1 b
2 c
3 d
{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


#### Numpy基础

In [16]:
# numpy数组构造
import numpy as np
print(np.array([1, 2, 3]))
# 生成等差数列
print(np.arange(0, 10, 2)) # 起始值, 终止值, 步长
print(np.linspace(1, 5, 11)) # 起始值, 终止值, 样本个数
# 特殊矩阵
print('全0矩阵')
print(np.zeros((2, 3))) # 全0矩阵
print('单位矩阵')
print(np.eye(3)) # 3*3单位矩阵
print(np.eye(3, k=1)) # 3*3单位矩阵, 偏移主对角线为1
print('对角矩阵')
print(np.diag([1, 2, 3])) # 对角矩阵
print('全10矩阵')
print(np.full((2, 3), 10)) # 全10矩阵
print('随机矩阵')
print(np.random.rand(2, 3)) # 随机矩阵0-1均匀分布
print(np.random.randn(2, 3)) # 随机矩阵标准正态分布
print(np.random.randint(0, 10, (2, 3))) # 随机矩阵整数均匀分布(2, 3)为维度
print(np.random.choice([10, 20, 30], (3, 3), p=[0.4, 0.2, 0.4]))# 以一定概率进行选择
print(np.random.permutation(['ustc', 'nico', 'edu', 'com'])) # 打散原列表

[1 2 3]
[0 2 4 6 8]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
全0矩阵
[[0. 0. 0.]
 [0. 0. 0.]]
单位矩阵
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
对角矩阵
[[1 0 0]
 [0 2 0]
 [0 0 3]]
全10矩阵
[[10 10 10]
 [10 10 10]]
随机矩阵
[[0.13371985 0.89374354 0.77169338]
 [0.98236722 0.73904041 0.30859929]]
[[-1.89460649 -0.25769103  0.1788687 ]
 [-1.18546341 -1.14782278 -1.84632015]]
[[1 7 3]
 [9 9 1]]
[[30 20 10]
 [20 20 20]
 [30 30 20]]
['edu' 'ustc' 'com' 'nico']


In [38]:
# numpy数组变形、合并等操作
# 转置
print(np.zeros((2,4)).T)
# 合并
print(np.r_[np.zeros((2, 3)), np.ones((2, 3))]) # 按行合并
print(np.c_[np.zeros((2, 3)), np.ones((2, 3))]) # 按列合并
print(np.c_[np.array([1,1]), np.zeros((2, 3))]) # 一维二维数组合并, 按列合并
# 维度变换 
print(np.random.randn(6).reshape((3, 2))) # 2*3变为3*2
print(np.random.randn(2,3).reshape(-1)) # reshape(-1)将多维数组变为一维数组, 允许一个维数空缺
# 数组切片
print(np.arange(9).reshape(3, 3))
print(np.arange(9).reshape(3, 3)[1:3, 1:3]) # 二维数组切片
print(np.arange(9).reshape(3, 3)[1:3, :]) # 二维数组切片
print(np.arange(9).reshape(3, 3)[np.ix_([1,2], [True, False, True])]) # 在对应的维度上使用布尔索引, 此时不能使用slice切片

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[-0.24454107  0.52428338]
 [ 0.7650059  -1.07872579]
 [ 0.13288399 -0.72405317]]
[-0.53593531 -0.87311507  0.19633392 -0.43977484 -0.36122564 -0.8701521 ]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[[3 4 5]
 [6 7 8]]
[[3 5]
 [6 8]]


In [55]:
# 常用函数
# where函数指定满足条件和不满足条件的填充值
print(np.where(np.arange(9).reshape(3, 3) > 0, 1, 0))
# 返回索引函数: nonzero, argmax, argmin
# nonzero返回非零元素的索引
print(np.nonzero(np.arange(9)))
# argmax返回最大值的索引
print(np.argmax(np.arange(9)))
# argmin返回最小值的索引
print(np.argmin(np.arange(9)))
# any函数: 当序列至少有一个True或非零元素时返回True
print(np.any(np.arange(2)))
# all函数: 当序列所有元素都为True或非零元素时返回True
print(np.all(np.arange(2)))
print(np.arange(1, 5))
# cumprod函数: 返回给定序列的累积乘法结果
print(np.cumprod(np.arange(1, 5)))
# cumsum函数: 返回给定序列的累积加法结果
print(np.cumsum(np.arange(1, 5)))
# diff函数: 返回给定序列的累积差值, 返回长度比原序列少1
print(np.diff(np.arange(1, 5)))
# 统计函数: sum, mean, std, var, max, min, median, average, quantile(全局函数, 不能通过array.quantile()调用)
print(np.quantile(np.arange(1, 5), 0.5)) # 返回给定序列的分位数, 这里是中位数
# 忽略有缺失值数组
print(np.array([1, 2, np.nan, 3]))
print(np.nansum(np.array([1, 2, np.nan, 3])))
print('协方差、相关系数的计算')
print(np.cov(np.array([1, 3, 5, 9]), np.array([1, 5, 3, -9]))) # 协方差
print(np.corrcoef(np.array([1, 2, 5]), np.array([2, 5, 6]))) # 相关系数
# 二维NUmpy数组的axis参数: axis=0表示列的统计指标; axis=1表示行的统计指标
print(np.arange(9).reshape(3, 3).sum(axis=0))
print(np.arange(9).reshape(3, 3).sum(axis=1))

[[0 1 1]
 [1 1 1]
 [1 1 1]]
(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)
8
0
True
False
[1 2 3 4]
[ 1  2  6 24]
[ 1  3  6 10]
[1 1 1]
2.5
[ 1.  2. nan  3.]
6.0
协方差、相关系数的计算
[[ 11.66666667 -16.66666667]
 [-16.66666667  38.66666667]]
[[1.         0.84615385]
 [0.84615385 1.        ]]
[ 9 12 15]
[ 3 12 21]


In [74]:
# 广播机制处理不同维度数组之间的操作
# 标量和数组的操作, 标量自动把大小扩充为数组大小
print(3 * np.random.rand(2, 3) + 2)
# 二维数组之间的操作, 其中一个维度实1*m或者n*1, 则自动扩充为m*n
print(np.ones((2, 3)) + np.zeros((1, 3)))
# 一维数组与二维数组的操作, 将一维数组视作1*m的二维数组
print(np.arange(3) + np.ones((3, 3)))
# 向量内积的计算
print(np.arange(3).dot(np.arange(2, 5)))
# 向量范数和矩阵范数
print(np.linalg.norm(np.arange(4).reshape(2, 2), 'fro'))
# 矩阵乘法
print(np.arange(4).reshape(2, 2) @ (np.arange(4).reshape(2, 2)))


[[4.35869895 4.31867726 3.80496064]
 [4.38257599 2.24020113 4.26423098]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
11
3.7416573867739413
[[ 2  3]
 [ 6 11]]


# Pandas基础

#### 文件读取和写入

In [11]:
import numpy as np
import pandas as pd
# 文件读取
# header=None表示不把第一行作为列名
df_csv = pd.read_csv('../data/my_csv.csv', parse_dates=['col5']) # parse_dates表示把某列作为日期
print(df_csv)
df_txt = pd.read_table('../data/my_table.txt', index_col=['col1', 'col3']) # 表示把某几列作为索引
print(df_txt)
df_excel = pd.read_excel('../data/my_excel.xlsx', usecols=['col3', 'col4', 'col5'], nrows=3) # 表示读取列的集合, 行数
print(df_excel)
print(pd.read_table('../data/my_table_special_sep.txt'))
print(pd.read_table('../data/my_table_special_sep.txt', sep=' \|\|\|\| ', engine='python')) # 使用sep指定分隔符, engine指定解析器
# 文件写入
df_csv.to_csv('../data/my_csv_saved.csv', index=False) # index=False表示不保存索引
df_excel.to_excel('../data/my_excel_saved.xlsx', index=False)
df_txt.to_csv('../data/my_txt_saved.txt', sep='\t', index=False) # sep指定分隔符, pandas没有to_table函数
# 表格转换
import tabulate
print(df_csv.to_markdown()) # 转换为markdown格式
print(df_csv.to_latex()) # 转换为latex格式

<>:12: SyntaxWarning: invalid escape sequence '\|'
<>:12: SyntaxWarning: invalid escape sequence '\|'
C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_17600\4037761022.py:12: SyntaxWarning: invalid escape sequence '\|'
  print(pd.read_table('../data/my_table_special_sep.txt', sep=' \|\|\|\| ', engine='python')) # 使用sep指定分隔符, engine指定解析器


   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05
3     5    d   3.2   lemon 2020-01-07
          col2             col4
col1 col3                      
2    1.4     a   apple 2020/1/1
3    3.4     b  banana 2020/1/2
6    2.5     c  orange 2020/1/5
5    3.2     d   lemon 2020/1/7
   col3    col4      col5
0   1.4   apple  2020/1/1
1   3.4  banana  2020/1/2
2   2.5  orange  2020/1/5
              col1 |||| col2
0  TS |||| This is an apple.
1    GQ |||| My name is Bob.
2         WT |||| Well done!
3    PT |||| May I help you?
  col1               col2
0   TS  This is an apple.
1   GQ    My name is Bob.
2   WT         Well done!
3   PT    May I help you?
|    |   col1 | col2   |   col3 | col4   | col5                |
|---:|-------:|:-------|-------:|:-------|:--------------------|
|  0 |      2 | a      |    1.4 | apple  | 2020-01-01 00:00:00 |
|  1 |      3 | b      |    3.4 | banana | 2

#### 基本数据结构

In [15]:
import numpy as np
import pandas as pd
# 存储一维的Series由序列值data、索引index、存储类型dtype、序列名字name四部分组成
# Series创建
series = pd.Series(data=[100, 'a', {'dict': 1}], index=pd.Index(['id1', 20, 'third'], name='my_series'), dtype='object', name='my_name')
print(series)
# 通过.获取属性
print(series.values)
print(series.index)
print(series.dtype)
print(series.name)
print('序列长度', series.shape)

# 存储二维的DataFrame由数据data、行索引index、列索引columns、存储类型dtype等组成
# DataFrame创建
dataframe = pd.DataFrame([[1, 'a', 1.2], [2, 'b', 2.2], [3, 'c', 3.2]], index=pd.Index(['row1', 'row2', 'row3'], name='my_rows'), columns=pd.Index(['id', 'name', 'score'], name='my_columns'))
print(dataframe)
# 取出列
print('提取列')
print(dataframe['id'])
print(dataframe[['name', 'score']])
# 取出行
print('提取行')
print(dataframe.loc['row1'])
# 通过.获取属性
print('获取属性')
print(dataframe.values)
print(dataframe.index)
print(dataframe.columns)
print(dataframe.dtypes)
print(dataframe.shape)
# 转置
print('转置dataframe')
print(dataframe.T)


my_series
id1              100
20                 a
third    {'dict': 1}
Name: my_name, dtype: object
[100 'a' {'dict': 1}]
Index(['id1', 20, 'third'], dtype='object', name='my_series')
object
my_name
序列长度 (3,)
my_columns  id name  score
my_rows                   
row1         1    a    1.2
row2         2    b    2.2
row3         3    c    3.2
提取列
my_rows
row1    1
row2    2
row3    3
Name: id, dtype: int64
my_columns name  score
my_rows               
row1          a    1.2
row2          b    2.2
row3          c    3.2
提取行
my_columns
id         1
name       a
score    1.2
Name: row1, dtype: object
获取属性
[[1 'a' 1.2]
 [2 'b' 2.2]
 [3 'c' 3.2]]
Index(['row1', 'row2', 'row3'], dtype='object', name='my_rows')
Index(['id', 'name', 'score'], dtype='object', name='my_columns')
my_columns
id         int64
name      object
score    float64
dtype: object
(3, 3)
转置dataframe
my_rows    row1 row2 row3
my_columns               
id            1    2    3
name          a    b    c
score       1.2  2.2

#### 基本函数

In [23]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/learn_pandas.csv')
print(df.columns)
# 提取前7列
df = df[df.columns[:7]]
print(df.columns)
# 汇总函数
print('汇总函数')
print(df.head(3)) # head函数返回前n行
print(df.tail(4)) # tail函数返回后n行
print(df.info()) # info函数返回信息概况
print(df.describe()) # describe函数返回数值列的汇总统计
# 特征统计函数
print('特征统计函数')
df_test = df[['Height', 'Weight']]
print(df_test.mean()) # mean函数返回均值
print(df_test.max()) # max函数返回最大值
print(df_test.quantile(0.75)) # quantile函数返回分位数
print(df_test.count()) # count函数返回非缺失值元素个数
print(df_test.idxmax()) # idxmax函数返回最大值的索引
print(df_test.mean(axis=1).head()) # axis=1表示按行统计
# 唯一值函数
print('唯一值函数')
print(df['School'].unique()) # unique函数返回唯一值数组
print(df['School'].nunique()) # nunique函数返回唯一值个数
print(df['School'].value_counts()) # value_counts函数返回唯一值计数
df_demo = df[['Gender', 'Transfer', 'Name']]
print(df_demo.drop_duplicates(['Gender', 'Transfer'], keep='last')) # drop_duplicates函数返回多个列的唯一值组合
print(df_demo.drop_duplicates(['Gender', 'Name'], keep=False).head()) # drop_duplicates函数返回多个列的唯一值组合, keep参数表示保留哪个值, False表示全部删除

Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer',
       'Test_Number', 'Test_Date', 'Time_Record'],
      dtype='object')
Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer'], dtype='object')
汇总函数
                          School     Grade            Name  Gender  Height  \
0  Shanghai Jiao Tong University  Freshman    Gaopeng Yang  Female   158.9   
1              Peking University  Freshman  Changqiang You    Male   166.5   
2  Shanghai Jiao Tong University    Senior         Mei Sun    Male   188.9   

   Weight Transfer  
0    46.0        N  
1    70.0        N  
2    89.0        N  
                            School      Grade            Name  Gender  Height  \
196            Tsinghua University     Senior         Li Zhao  Female   160.9   
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua Universi

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('../data/learn_pandas.csv')
# 提取前7列
df = df[df.columns[:7]]
# 替换函数
print('替换函数')
print(df['Gender'].replace({'Female':0, 'Male':1}).head()) # 通过字典替换
print(df['Gender'].replace(['Female', 'Male'], [0, 1]).head()) # 通过列表替换
series = pd.Series([1, 2, 'a', 1, 2, 'b'])
print(series.replace([1, 2], method='bfill')) # method参数表示用后一个最近未被替换的值进行替换
print(series.replace([1, 2], method='ffill')) # method参数表示用前一个最近未被替换的值进行替换
# 逻辑替换
print('逻辑替换')
series = pd.Series([-1, 1.2345, 100, -50])
print(series.where(series<0)) # where函数返回满足条件的值, 不指定值时不满足的值用NaN填充
print(series.where(series<0, 0)) # where函数返回满足条件的值, 指定值时不满足的值用指定值填充
print(series.mask(series<0)) # mask函数返回不满足条件的值, 不指定值时满足的值用NaN填充
print(series.mask(series<0, 0)) # mask函数返回不满足条件的值, 指定值时满足的值用指定值填充
# 数值替换
print('数值替换')
print(series)
print(series.round(2)) # round函数返回指定精度的四舍五入值
print(series.abs()) # abs函数返回绝对值
print(series.clip(0, 2)) # clip函数返回截断值, 小于0的值替换为0, 大于2的值替换为2
# 排序函数
print('排序函数')
df_test = df[['Grade', 'Name', 'Height', 'Weight']].set_index(['Grade', 'Name']) # 把年级和名字当成索引
print(df_test.sort_values('Height').head()) # sort_values函数返回按指定列排序的结果
print(df_test.sort_values('Height', ascending=False).head()) # sort_values函数返回按指定列排序的结果, ascending参数表示升序或降序
# 多列排序
print('多列排序')
print(df_test.sort_values(['Weight', 'Height'], ascending=[True, False]).head()) # sort_values函数返回按指定列排序的结果, ascending参数表示升序或降序
# 索引排序
print('索引排序')
print(df_test.sort_index(level=['Grade', 'Name'], ascending=[True, False]).head()) # sort_index函数返回按指定索引排序的结果, level参数表示索引层级, ascending参数表示升序或降序
# apply方法, 用于DataFrame的行/列的迭代
print('apply方法')
df_demo = df[['Height', 'Weight']]
print(df_demo.apply(lambda x: x.mean())) # apply函数返回对每一列应用函数的结果
print(df_demo.apply(lambda x: x.mean(), axis=1).head()) # apply函数返回对每一行应用函数的结果

替换函数
0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64
0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64
0    a
1    a
2    a
3    b
4    b
5    b
dtype: object
0    1
1    1
2    a
3    a
4    a
5    b
dtype: object
逻辑替换
0    -1.0
1     NaN
2     NaN
3   -50.0
dtype: float64
0    -1.0
1     0.0
2     0.0
3   -50.0
dtype: float64
0         NaN
1      1.2345
2    100.0000
3         NaN
dtype: float64
0      0.0000
1      1.2345
2    100.0000
3      0.0000
dtype: float64
数值替换
0     -1.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64
0     -1.00
1      1.23
2    100.00
3    -50.00
dtype: float64
0      1.0000
1      1.2345
2    100.0000
3     50.0000
dtype: float64
0    0.0000
1    1.2345
2    2.0000
3    0.0000
dtype: float64
排序函数
                         Height  Weight
Grade     Name                         
Junior    Xiaoli Chu      145.4    34.0
Senior    Gaomei Lv       147.3    34.0
Sophomore Peng Han        147.8    34.0
Senior    Changli Lv    

C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_10104\1982048481.py:11: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  print(series.replace([1, 2], method='bfill')) # method参数表示用后一个最近未被替换的值进行替换
C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_10104\1982048481.py:12: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  print(series.replace([1, 2], method='ffill')) # method参数表示用前一个最近未被替换的值进行替换


#### 窗口对象

In [19]:
import numpy as np
import pandas as pd
# 滑窗对象rolling
print('滑窗对象')
series = pd.Series([1, 2, 6, 16, 30])
roller = series.rolling(window=2) # window参数表示窗口大小
print(roller)
print('聚合函数的使用')
print(roller.mean()) # mean函数返回滑窗平均值
print('均值使用apply实现')
print(roller.apply(lambda x: x.mean())) # apply函数返回滑窗平均值
print(roller.sum()) # sum函数返回滑窗和
print(roller.cov(series)) # cov函数返回滑窗协方差
print(roller.corr(series)) # corr函数返回滑窗相关系数
# 下面三个类滑窗函数的参数n可以为负值, 代表反方向操作
print(series.shift(3)) # 取向前第n个元素
print(series.diff(1)) # 与向前第n个元素的差值
print(series.pct_change(3)) # 与向前第n个元素相比计算增长率

# 扩张窗口
print('扩张窗口')
print(series.expanding(3).sum()) # expanding函数返回扩张窗口的和(窗口逐步扩张)

滑窗对象
Rolling [window=2,center=False,axis=0,method=single]
聚合函数的使用
0     NaN
1     1.5
2     4.0
3    11.0
4    23.0
dtype: float64
均值使用apply实现
0     NaN
1     1.5
2     4.0
3    11.0
4    23.0
dtype: float64
0     NaN
1     3.0
2     8.0
3    22.0
4    46.0
dtype: float64
0     NaN
1     0.5
2     8.0
3    50.0
4    98.0
dtype: float64
0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64
0    NaN
1    NaN
2    NaN
3    1.0
4    2.0
dtype: float64
0     NaN
1     1.0
2     4.0
3    10.0
4    14.0
dtype: float64
0     NaN
1     NaN
2     NaN
3    15.0
4    14.0
dtype: float64
扩张窗口
0     NaN
1     NaN
2     9.0
3    25.0
4    55.0
dtype: float64


# 索引

#### 索引器

In [29]:
import numpy as np
import pandas as pd
# 列索引, 一般通过[]实现
print('列索引')
df = pd.read_csv('../data/learn_pandas.csv', usecols=['School', 'Grade', 'Name', 'Gender', 'Weight', 'Transfer'])
print(df['Name'].head())
print(df.Name.head()) # 通过.实现(要求列名不能有空格)
print(df[['School', 'Name']].head()) # 取出多个

# 行索引
print('行索引')
series = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'a', 'e']) # 以字符串为索引的series
print(series['a']) # 通过[item]实现单个索引对应元素
print(series[['a', 'b']]) # 通过[item1, item2]实现多个索引对应元素
print(series['b':'e']) # 通过[item1:item2]实现切片索引对应元素,要求索引唯一出现
print(series.sort_index()['a':'b']) # 有重复元素排序后可以使用切片索引
series = pd.Series(['a', 'b', 'c', 'd', 'e', 'f'], index=[1, 3, 1, 2, 5, 4]) # 以数字为索引的series(默认就是以数字为索引)
print(series[1]) # 通过[item]实现单个索引对应元素
print(series[0:5:2]) # 通过[item1:item2:step]实现切片索引对应元素

# loc索引器, 基于元素, loc[index, column], 省略column表示取出所有列进行行的筛选
print('loc索引器')
df_test = df.set_index('Name')
print(df_test.head())
# 对单个元素进行操作
print('重名')
print(df_test.loc['Qiang Sun']) # 重名
print('无重名')
print(df_test.loc['Quan Zhao']) # 无重名
print(df_test.loc['Qiang Sun', 'Gender']) # 同时选择行和列
# 对元素列表进行操作
print(df_test.loc[['Qiang Sun', 'Quan Zhao'], ['Gender', 'Weight']])
# 对元素切片进行操作
print(df_test.loc['Gaojuan You':'Gaoqiang Qian', 'School':'Gender'])
# 对布尔列表进行操作, 可以通过与或非操作得到布尔列表
print(df_test.loc[df_test.Weight>60].head())
print(df_test.loc[df_test.Grade.isin(['Freshman', 'Senior'])].head()) # 利用isin()方法构造布尔列表
# 对函数进行操作
print(df_test.loc[lambda x: x.Weight<60].head()) 
print(df_test.loc[lambda x: slice('Gaojuan You', 'Gaoqiang Qian')]) # 利用切片构造函数

列索引
0      Gaopeng Yang
1    Changqiang You
2           Mei Sun
3      Xiaojuan Sun
4       Gaojuan You
Name: Name, dtype: object
0      Gaopeng Yang
1    Changqiang You
2           Mei Sun
3      Xiaojuan Sun
4       Gaojuan You
Name: Name, dtype: object
                          School            Name
0  Shanghai Jiao Tong University    Gaopeng Yang
1              Peking University  Changqiang You
2  Shanghai Jiao Tong University         Mei Sun
3               Fudan University    Xiaojuan Sun
4               Fudan University     Gaojuan You
行索引
a    1
a    4
dtype: int64
a    1
a    4
b    2
dtype: int64
b    2
c    3
a    4
e    5
dtype: int64
a    1
a    4
b    2
dtype: int64
1    a
1    c
dtype: object
1    a
1    c
5    e
dtype: object
loc索引器
                                       School      Grade  Gender  Weight  \
Name                                                                       
Gaopeng Yang    Shanghai Jiao Tong University   Freshman  Female    46.0   
Changqiang Y

In [44]:
import numpy as np
import pandas as pd
# iloc索引器, 基于位置(与loc类似)
print('iloc索引器')
df = pd.read_csv('../data/learn_pandas.csv', usecols=['School', 'Grade', 'Name', 'Gender', 'Weight', 'Transfer'])
df_test = df.set_index('Name')
# 对单个元素进行操作
print(df_test.iloc[1, 2]) # 同时选择行和列
# 对元素列表进行操作
print(df_test.iloc[[1, 2], [2, 3]])
# 对元素切片进行操作
print(df_test.iloc[1:3, 2:4]) # 不包含结束端点
print(df_test.iloc[lambda x: slice(1, 4)]) 
# 对布尔列表进行操作
print(df_test.iloc[(df_test.Weight>60).values].head()) # 注意传入的是values

# query方法
print('query方法')
print(df.query('((School == "Fudan University")&'
         ' (Grade == "Senior")&'
         ' (Weight > 70))|'
         '((School == "Peking University")&'
         ' (Grade != "Senior")&'
         ' (Weight > 80))'))
print(df.query('Weight > Weight.mean()').head())
print(df.query('Grade not in ["Freshman", "Senior"]').head()) # 英语字面用法
print(df.query('Grade == ["Freshman", "Senior"]').head()) # ==表示元素出现在列表中
low, high = 60, 80
print(df.query('(Weight > @low) & (Weight < @high)').head()) # @表示引用外部变量

# 随机抽样(行可以看成一个样本, 列可以看成一个特征)
print('随机抽样')
df_sample = pd.DataFrame({'id' : list('abcde'), 'value' : [1, 2, 3, 4, 5]})
print(df_sample)
print(df_sample.sample(n=3, replace=True, weights=df_sample.value)) # n参数表示抽样的数量, replace参数表示是否放回抽样, weights参数表示抽样的概率, axis表示抽样方向, frac表示抽样比例

iloc索引器
Male
               Gender  Weight
Name                         
Changqiang You   Male    70.0
Mei Sun          Male    89.0
               Gender  Weight
Name                         
Changqiang You   Male    70.0
Mei Sun          Male    89.0
                                       School      Grade  Gender  Weight  \
Name                                                                       
Changqiang You              Peking University   Freshman    Male    70.0   
Mei Sun         Shanghai Jiao Tong University     Senior    Male    89.0   
Xiaojuan Sun                 Fudan University  Sophomore  Female    41.0   

               Transfer  
Name                     
Changqiang You        N  
Mei Sun               N  
Xiaojuan Sun          N  
                                       School      Grade Gender  Weight  \
Name                                                                      
Changqiang You              Peking University   Freshman   Male    70.0   
Mei Sun    

#### 多级索引

In [12]:
import numpy as np
import pandas as pd
# 多级索引及其表的构造
print('多级索引及其表的构造')
np.random.seed(0)
df = pd.read_csv('../data/learn_pandas.csv')
# 构造多级索引表, 索引是一个元组
multi_index = pd.MultiIndex.from_product([list('ABCD'), df.Gender.unique()], names=('School', 'Gender'))
multi_column = pd.MultiIndex.from_product([['Height', 'Weight'], df.Grade.unique()], names=('Indicator', 'Grade'))
df_multi = pd.DataFrame(np.c_[(np.random.randn(8, 4)*5 + 163).tolist(), (np.random.randn(8, 4)*5 + 65).tolist()], index=multi_index, columns=multi_column).round(1)
print(df_multi)
print('行索引名字:', df_multi.index.names)
print('行索引值属性:', df_multi.index.values)
print('某一层索引:', df_multi.index.get_level_values(0))

# 多级索引里的loc索引器
print('多级索引里的loc索引器')
df_multi2 = df.set_index(['School', 'Grade']) # 以School和Grade为行索引(多级索引)
print(df_multi2.head())
df_sorted = df_multi2.sort_index() # 对多级索引进行排序
print(df_sorted.loc[('Fudan University', 'Freshman')].head())
print(df_sorted.loc[[('Tsinghua University', 'Freshman'), ('Fudan University', 'Senior')]].head())
print(df_sorted.loc[df_sorted.Weight<70].head())
print(df_sorted.loc[lambda x: x.Weight<70].head())
# 使用切片之前一定要对多级索引排序, 否则报错
print(df_sorted.loc[('Tsinghua University', 'Freshman'):('Tsinghua University', 'Senior')].head())
# 对多层元素进行交叉组合后索引, 同时要指定loc的列, 全选用:表示
print(df_multi2.loc[(['Tsinghua University', 'Peking University'], ['Freshman', 'Junior']), :].head())

多级索引及其表的构造
Indicator       Height                           Weight                   \
Grade         Freshman Senior Sophomore Junior Freshman Senior Sophomore   
School Gender                                                              
A      Female    171.8  165.0     167.9  174.2     60.6   55.1      63.3   
       Male      172.3  158.1     167.8  162.2     71.2   71.0      63.1   
B      Female    162.5  165.1     163.7  170.3     59.8   57.9      56.5   
       Male      166.8  163.6     165.2  164.7     62.5   62.8      58.7   
C      Female    170.5  162.0     164.6  158.7     56.9   63.9      60.5   
       Male      150.2  166.3     167.3  159.3     62.4   59.1      64.9   
D      Female    174.3  155.7     163.2  162.1     65.3   66.5      61.8   
       Male      170.7  170.3     163.8  164.9     61.6   63.2      60.9   

Indicator             
Grade         Junior  
School Gender         
A      Female   65.8  
       Male     63.5  
B      Female   74.8  
       Male   

In [26]:
import numpy as np
import pandas as pd
# IndexSlice对象
print('IndexSlice对象')
np.random.seed(0)
L1,L2 = ['A', 'B'], ['a', 'b']
multi_index1 = pd.MultiIndex.from_product([L1, L2], names=('Upper', 'Lower'))
L3,L4 = ['C', 'D'], ['c', 'd']
multi_index2 = pd.MultiIndex.from_product([L3, L4], names=('Big', 'Small'))
df_test = pd.DataFrame(np.random.randint(-10, 10, (4, 4)), index=multi_index1, columns=multi_index2)
print(df_test)
idx = pd.IndexSlice # 定义IndexSlice对象
# loc[idx[行索引, 列索引]]型
print(df_test.loc[idx['B':, ('C', 'd'):]])
print(df_test.loc[idx[:'A', lambda x: x.sum()>0]]) # 列和大于0
# loc[idx[*, *], idx[*, *]]型, 前一个idx表示行索引, 后一个idx表示列索引, 不支持函数
print(df_test.loc[idx[:, 'b':], idx['C':, 'd':]])

# 多级索引的构造
print('多级索引的构造')
# 通过from_tuples构造
my_tuple = [('a', 'cat'), ('a', 'dog'), ('b', 'cat'), ('b', 'dog')]
print(pd.MultiIndex.from_tuples(my_tuple, names=('First', 'Second')))
# 通过from_arrays构造
my_array = [['a', 'a', 'b', 'b'], ['cat', 'dog', 'cat', 'dog']]
print(pd.MultiIndex.from_arrays(my_array, names=('First', 'Second')))
# 通过from_product构造, 根据给定的多个列表的笛卡尔积构造
my_list1 = ['a', 'b']
my_list2 = ['cat', 'dog']
print(pd.MultiIndex.from_product([my_list1, my_list2], names=('First', 'Second')))

IndexSlice对象
Big          C      D   
Small        c  d   c  d
Upper Lower             
A     a      2  5 -10 -7
      b     -7 -3  -1  9
B     a      8 -6  -4  2
      b     -9 -4  -3  4
Big          C  D   
Small        d  c  d
Upper Lower         
B     a     -6 -4  2
      b     -4 -3  4
Big          D
Small        d
Upper Lower   
A     a     -7
      b      9
Big          C  D
Small        d  d
Upper Lower      
A     b     -3  9
B     b     -4  4
多级索引的构造
MultiIndex([('a', 'cat'),
            ('a', 'dog'),
            ('b', 'cat'),
            ('b', 'dog')],
           names=['First', 'Second'])
MultiIndex([('a', 'cat'),
            ('a', 'dog'),
            ('b', 'cat'),
            ('b', 'dog')],
           names=['First', 'Second'])
MultiIndex([('a', 'cat'),
            ('a', 'dog'),
            ('b', 'cat'),
            ('b', 'dog')],
           names=['First', 'Second'])


#### 索引的常用方法

In [43]:
import numpy as np
import pandas as pd
# 索引层的删除和交换
np.random.seed(0)
L1,L2,L3 = ['A', 'B'], ['a', 'b'], ['alpha', 'beta']
multi_idx1 = pd.MultiIndex.from_product([L1, L2, L3], names=('Upper', 'Lower', 'Extra'))
L4,L5,L6 = ['C', 'D'], ['c', 'd'], ['cat', 'dog']
multi_idx2 = pd.MultiIndex.from_product([L4, L5, L6], names=('Big', 'Small', 'Other'))
df_test = pd.DataFrame(np.random.randint(-10, 10, (8, 8)), index=multi_idx1, columns=multi_idx2)
print(df_test)
print('索引层的交换')
print(df_test.swaplevel(2, 0, axis=1)) # swaplevel()函数交换两个层级的索引, axis参数表示交换的方向
print(df_test.reorder_levels([2, 0, 1], axis=0)) # reorder_levels()函数交换多个层级的索引, axis参数表示交换的方向
print('索引层的删除')
print(df_test.droplevel(1, axis=1)) # droplevel()函数删除指定层级的索引, axis参数表示删除的方向
print(df_test.droplevel([1, 2], axis=0)) # droplevel()函数删除多个层级的索引, axis参数表示删除的方向

# 索引属性的修改
print('索引属性的修改')
print(df_test.rename_axis(index={'Upper': 'Changed_row'}, columns={'Big': 'Changed_col'})) # rename_axis()函数修改索引的名字, 传入字典的映射
print(df_test.rename(columns={'dog':'DOG'}, level=2)) # rename()函数修改索引的名字, level表示层级
print(df_test.rename(index=lambda x: str.upper(x), level=2)) # rename()函数修改索引的名字, 传入函数
new_values = iter(list('ABCDEFGH')) # 迭代器必须提前创建, 否则每次调用lambda函数都会从头开始创建迭代器
print(df_test.rename(index=lambda x: next(new_values), level=2)) # 使用迭代器完成整个索引的修改
df_tmp = df_test.copy()
new_index = df_tmp.index.map(lambda x: (x[0], x[1], x[2].upper())) # map()函数修改索引的值, 传入函数
df_tmp.index = new_index
print(df_tmp)
new_index = df_tmp.index.map(lambda x: (x[0]+'_'+x[1]+'_'+x[2])) # 压缩多级索引
df_tmp.index = new_index
print(df_tmp)

Big                 C               D            
Small               c       d       c       d    
Other             cat dog cat dog cat dog cat dog
Upper Lower Extra                                
A     a     alpha   2   5 -10  -7  -7  -3  -1   9
            beta    8  -6  -4   2  -9  -4  -3   4
      b     alpha   7  -5   3  -2  -1   9   6   9
            beta   -5   5   5 -10   8  -7   7   9
B     a     alpha   9   9   4  -3 -10  -9  -1 -10
            beta    0  -7   1   8  -8 -10 -10  -6
      b     alpha  -5  -4  -2   7   5  -6  -1   0
            beta   -9  -9  -3  -1  -7  -4   1   4
索引层的交换
Other             cat dog cat dog cat dog cat dog
Small               c   c   d   d   c   c   d   d
Big                 C   C   C   C   D   D   D   D
Upper Lower Extra                                
A     a     alpha   2   5 -10  -7  -7  -3  -1   9
            beta    8  -6  -4   2  -9  -4  -3   4
      b     alpha   7  -5   3  -2  -1   9   6   9
            beta   -5   5   5 -10   8  -7  

In [61]:
import numpy as np
import pandas as pd
# 索引的设置与重置
print('索引的设置与重置')
df = pd.DataFrame({'A': list('aacd'), 'B': list('PQRT'), 'C': [1, 2, 3, 4]})
print(df)
print(df.set_index('B')) # set_index()函数设置索引
print(df.set_index('B', append=True)) # set_index()函数设置索引, append参数表示是否保留原索引
print(df.set_index(['B', 'C'])) # set_index()函数设置多级索引
index = pd.Series(list('WXYZ'), name='D')
print(df.set_index(['B', index])) # set_index()函数设置多级索引, 传入Series添加新的索引
df = df.set_index(['B', index])
print(df.reset_index(['B'])) # reset_index()函数重置索引
print(df.reset_index(['B'], drop=True)) # reset_index()函数重置索引, drop参数表示是否删除索引列

# 索引的变形
print('索引的变形')
df_reidx = pd.DataFrame({'Weight':[55,60,65],'Height':[165,170,175]},index=pd.Index(['1001','1002','1003']))
print(df_reidx)
print(df_reidx.reindex(index=['1001', '1002', '1003', '1004'], columns=['Weight', 'Gender']))
df_ = pd.DataFrame(index=['1001', '1002', '1003', '1004'], columns=['Weight', 'Gender'])
print(df_reidx.reindex_like(df_)) # reindex_like()函数按照另一个表的索引进行变形

索引的设置与重置
   A  B  C
0  a  P  1
1  a  Q  2
2  c  R  3
3  d  T  4
   A  C
B      
P  a  1
Q  a  2
R  c  3
T  d  4
     A  C
  B      
0 P  a  1
1 Q  a  2
2 R  c  3
3 T  d  4
     A
B C   
P 1  a
Q 2  a
R 3  c
T 4  d
     A  C
B D      
P W  a  1
Q X  a  2
R Y  c  3
T Z  d  4
   B  A  C
D         
W  P  a  1
X  Q  a  2
Y  R  c  3
Z  T  d  4
   A  C
D      
W  a  1
X  a  2
Y  c  3
Z  d  4
索引的变形
      Weight  Height
1001      55     165
1002      60     170
1003      65     175
      Weight  Gender
1001    55.0     NaN
1002    60.0     NaN
1003    65.0     NaN
1004     NaN     NaN
      Weight  Gender
1001    55.0     NaN
1002    60.0     NaN
1003    65.0     NaN
1004     NaN     NaN


#### 索引运算

In [63]:
import numpy as np
import pandas as pd
df_set1 = pd.DataFrame([[1,2], [2,3], [3,4]], index=pd.Index(['a', 'b', 'a'], name='id1'))
df_set2 = pd.DataFrame([[4,5], [2,6], [1,7]], index=pd.Index(['b', 'b', 'c'], name='id2'))
id1, id2 = df_set1.index.unique(), df_set2.index.unique()
print(id1.intersection(id2)) # intersection()函数返回两个索引的交集
print(id1.union(id2)) # union()函数返回两个索引的并集
print(id1.difference(id2)) # difference()函数返回两个索引的差集
print(id1.symmetric_difference(id2)) # symmetric_difference()函数返回两个索引的对称差集
print(id1.isin(id2)) # isin()函数返回id1中的元素是否在id2中

Index(['b'], dtype='object')
Index(['a', 'b', 'c'], dtype='object')
Index(['a'], dtype='object')
Index(['a', 'c'], dtype='object')
[False  True]


# 分组

#### 分组模式及其对象

In [3]:
import numpy as np
import pandas as pd
# df.groupby(分组依据)[数据来源].使用操作
df = pd.read_csv('../data/learn_pandas.csv')   
print(df.groupby('Gender')['Height'].mean()) # 按性别分组, 计算身高均值
print(df.groupby(['Gender', 'School'])['Height'].mean()) # 多个分组依据
condition = df.Weight > df.Weight.median()
print(df.groupby(condition)['Height'].mean()) # 按条件分组
print(df[['School', 'Gender']].drop_duplicates())

# groupby对象
print('groupby对象')
gb = df.groupby(['School', 'Grade']) # groupby对象
print(gb)
print(gb.ngroups) # ngroups属性返回分组的个数
print(gb.groups) # groups属性返回分组的字典
dic = gb.groups
print(dic.keys()) # keys()方法返回分组的键
print(gb.size()) # size()方法统计每个组的元素个数
print(gb.get_group(('Tsinghua University', 'Freshman')).iloc[:3, :4]) # get_group()方法返回指定组的数据

Gender
Female    159.19697
Male      173.62549
Name: Height, dtype: float64
Gender  School                       
Female  Fudan University                 158.776923
        Peking University                158.666667
        Shanghai Jiao Tong University    159.122500
        Tsinghua University              159.753333
Male    Fudan University                 174.212500
        Peking University                172.030000
        Shanghai Jiao Tong University    176.760000
        Tsinghua University              171.638889
Name: Height, dtype: float64
Weight
False    157.811881
True     169.876829
Name: Height, dtype: float64
                           School  Gender
0   Shanghai Jiao Tong University  Female
1               Peking University    Male
2   Shanghai Jiao Tong University    Male
3                Fudan University  Female
4                Fudan University    Male
5             Tsinghua University  Female
9               Peking University  Female
16            Tsinghua Univer

#### 聚合函数

In [12]:
import numpy as np
import pandas as pd
# 内置聚合函数
print('内置聚合函数')
df = pd.read_csv('../data/learn_pandas.csv')
gb = df.groupby('Gender')['Height']
print(gb.idxmin()) # idxmin()方法返回最小值的索引
print(gb.quantile(0.8)) # quantile()方法返回分位数
gb = df.groupby('Gender')[['Height', 'Weight']] # 多列分组
print(gb.max()) # max()方法返回最大值, 按照列迭代计算

# agg方法
print('agg方法')
print(gb.agg(['sum', 'idxmax', 'skew'])) # 使用多个函数, agg()方法返回多个聚合结果
print(gb.agg({'Height':['mean', 'max'], 'Weight':'count'})) # 使用字典, 对特定的列使用特定的聚合函数
print(gb.agg(lambda x: x.max()-x.min())) # 使用函数, 函数的参数是数据源的列, 逐列进行计算
print(gb.agg([('range', lambda x: x.max()-x.min()), ('my_func', 'mean')])) # 使用元组对聚合结果重命名, 元组的第一个元素是列名, 第二个元素是函数
print(gb.agg({'Height': [('my_func', 'mean'), 'max'], 'Weight': [('range', lambda x: x.count())]})) # 使用字典对聚合结果重命名, 重命名需要加方括号

内置聚合函数
Gender
Female    143
Male      199
Name: Height, dtype: int64
Gender
Female    163.78
Male      177.30
Name: Height, dtype: float64
        Height  Weight
Gender                
Female   170.2    63.0
Male     193.9    89.0
agg方法
         Height                   Weight                 
            sum idxmax      skew     sum idxmax      skew
Gender                                                   
Female  21014.0     28 -0.219253  6469.0     28 -0.268482
Male     8854.9    193  0.437535  3929.0      2 -0.332393
           Height        Weight
             mean    max  count
Gender                         
Female  159.19697  170.2    135
Male    173.62549  193.9     54
        Height  Weight
Gender                
Female    24.8    29.0
Male      38.2    38.0
       Height            Weight           
        range    my_func  range    my_func
Gender                                    
Female   24.8  159.19697   29.0  47.918519
Male     38.2  173.62549   38.0  72.759259
      

#### 变换和过滤

In [28]:
import numpy as np
import pandas as pd
# 变换函数和tranform方法
print('变换函数和tranform方法')
df = pd.read_csv('../data/learn_pandas.csv')
gb = df.groupby('Gender')[['Height', 'Weight']]
print(gb.cummax().head()) # cummax()方法返回累计最大值
print(gb.transform(lambda x: (x - x.mean())/x.std()).head()) # transform()方法返回变换后的结果, 函数的参数是数据源的列, 逐列进行计算

# 组索引和过滤
print(gb.filter(lambda x: x.shape[0] < 80).head()) # 函数的输入为DataFrame, 返回布尔值, 逐组进行判断, 返回True的组保留, 返回False的组丢弃

变换函数和tranform方法
   Height  Weight
0   158.9    46.0
1   166.5    70.0
2   188.9    89.0
3     NaN    46.0
4   188.9    89.0
     Height    Weight
0 -0.058760 -0.354888
1 -1.010925 -0.355000
2  2.167063  2.089498
3       NaN -1.279789
4  0.053133  0.159631
    Height  Weight
1    166.5    70.0
2    188.9    89.0
4    174.0    74.0
10   174.1    74.0
16   170.1    68.0


#### 跨列分组

In [31]:
import numpy as np
import pandas as pd
df = pd.read_csv('../data/learn_pandas.csv')
# apply方法
# 标量情况: 结果得到的是Series
gb = df.groupby(['Gender', 'Test_Number'])[['Height', 'Weight']]
print(gb.apply(lambda x: 0))
print(gb.apply(lambda x: [0, 0]))
# Series情况: 结果得到的是DataFrame, 行索引与标量情况一致, 列索引为Series的索引
print(gb.apply(lambda x: pd.Series([0, 0], index=['a', 'b'])))
# DataFrame情况: 结果得到的是DataFrame, 行索引最内层在每个组原先的agg上再加一层返回的DataFrame行索引, 列索引为DataFrame的列索引
print(gb.apply(lambda x: pd.DataFrame(np.ones((2, 2)), index=['a', 'b'], columns=pd.Index([('w', 'x'), ('y', 'z')]))))

Gender  Test_Number
Female  1              0
        2              0
        3              0
Male    1              0
        2              0
        3              0
dtype: int64
Gender  Test_Number
Female  1              [0, 0]
        2              [0, 0]
        3              [0, 0]
Male    1              [0, 0]
        2              [0, 0]
        3              [0, 0]
dtype: object
                    a  b
Gender Test_Number      
Female 1            0  0
       2            0  0
       3            0  0
Male   1            0  0
       2            0  0
       3            0  0
                        w    y
                        x    z
Gender Test_Number            
Female 1           a  1.0  1.0
                   b  1.0  1.0
       2           a  1.0  1.0
                   b  1.0  1.0
       3           a  1.0  1.0
                   b  1.0  1.0
Male   1           a  1.0  1.0
                   b  1.0  1.0
       2           a  1.0  1.0
                   b  1.0  1.0


# 变形

#### 长宽表的变形

In [14]:
import numpy as np
import pandas as pd

# 长表, 如果把某一特征存储在某一列中, 则就是关于该特征的长表
print(pd.DataFrame({'Gender': ['F', 'M', 'M', 'F'], 'Height': [163, 178, 173, 165]}))
# 宽表, 如果把某一特征存储在多列中(列中的元素是某一其他的相关特征数值), 则就是关于该特征的宽表
print(pd.DataFrame({'Height: F':[163, 160], 'Height: M':[178, 173]}))

# pivot方法, 需要满足唯一性需求(即行列索引组合唯一),否则报错
print('pivot方法')
df = pd.DataFrame({'Class': [1,2,1,2], 'Name':['San Zhang', 'San Zhang', 'Si Li', 'Si Li'], 'Subject':['Chinese', 'Math', 'Chinese', 'Math'], 'Grade':[80, 75, 90, 85]})
print(df)
print(df.pivot(index='Name', columns='Subject', values='Grade')) # pivot()方法返回以index的unique值为行索引, columns的unique值为列索引, values为值的表
df = pd.DataFrame({'Class':[1,1,2,2,1,1,2,2],'Name':['San Zhang', 'San Zhang', 'Si Li', 'Si Li', 'San Zhang', 'San Zhang', 'Si Li', 'Si Li'], 'Examination': ['Mid', 'Final', 'Mid', 'Final', 'Mid', 'Final', 'Mid', 'Final'], 'Subject':['Chinese', 'Chinese', 'Chinese', 'Chinese', 'Math', 'Math', 'Math', 'Math'], 'Grade':[70, 80, 65, 90, 85, 75, 60, 88], 'rank':[10, 15, 20, 14, 20, 7, 6, 3]})
print(df)
print(df.pivot(index=['Class', 'Name'], columns=['Subject', 'Examination'], values=['Grade', 'rank'])) # 传入列表, 生成多级索引

# pivot_table方法
print('pivot_table方法')
# 行列索引组合不唯一的情况
df = pd.DataFrame({'Name':['San Zhang', 'San Zhang', 'San Zhang', 'San Zhang', 'Si Li', 'Si Li', 'Si Li', 'Si Li'], 'Subject':['Chinese', 'Chinese', 'Math', 'Math', 'Chinese', 'Chinese', 'Math', 'Math'], 'Grade':[80, 75, 90, 85, 100, 99, 87, 91]})
print(df)
print(df.pivot_table(index='Name', columns='Subject', values='Grade', aggfunc='mean')) # pivot_table()方法返回以index的unique值为行索引, columns的unique值为列索引, values为值的表, aggfunc参数表示聚合函数(使相同的行列组合对应的多个值变为一个值)
print(df.pivot_table(index='Name', columns='Subject', values='Grade', aggfunc='mean', margins=True)) # pivot_table具有边际汇总的功能, 边际汇总的聚合方式与aggfunc相同 

# melt方法, 将宽表转为长表
print('melt方法')
df = pd.DataFrame({'Class':[2,1], 'Name':['Terence', 'Lily'], 'English':[90,91], 'Math':[89, 92]})
print(df)
print(df.melt(id_vars=['Class', 'Name'], value_vars=['English', 'Math'], var_name='Subject', value_name='Grade')) # id_vars参数表示保持不变的列, value_vars参数表示要转换的列, var_name参数表示转换后的列名, value_name参数表示转换后的值名
df_melt = df.melt(id_vars=['Class', 'Name'], value_vars=['English', 'Math'], var_name='Subject', value_name='Grade')
print(df_melt.pivot(index=['Class','Name'], columns='Subject', values='Grade')) # 逆操作
df_melt = df_melt.pivot(index=['Class','Name'], columns='Subject', values='Grade')
df_melt = df_melt.reset_index().rename_axis(columns={'Subject':''}) # 重置索引, 重命名列索引
print(df_melt)

# wide_to_long方法, 将宽表转为长表(适用于列中包含了交叉类别)
print('wide_to_long方法')
df = pd.DataFrame({'Class':[2,1], 'Name':['Terence', 'Lily'], 'English_Mid':[90,91], 'Math_Mid':[89, 92], 'English_Final':[92, 93], 'Math_Final':[94, 95]})
print(df)
print(pd.wide_to_long(df, stubnames=['English', 'Math'], i=['Class', 'Name'], j='Examination', sep='_', suffix='.+')) # stubnames参数表示列名的前缀, i参数表示保持不变的列, j参数表示转换后的列名, sep参数表示分隔符, suffix参数表示列名的后缀

  Gender  Height
0      F     163
1      M     178
2      M     173
3      F     165
   Height: F  Height: M
0        163        178
1        160        173
pivot方法
   Class       Name  Subject  Grade
0      1  San Zhang  Chinese     80
1      2  San Zhang     Math     75
2      1      Si Li  Chinese     90
3      2      Si Li     Math     85
Subject    Chinese  Math
Name                    
San Zhang       80    75
Si Li           90    85
   Class       Name Examination  Subject  Grade  rank
0      1  San Zhang         Mid  Chinese     70    10
1      1  San Zhang       Final  Chinese     80    15
2      2      Si Li         Mid  Chinese     65    20
3      2      Si Li       Final  Chinese     90    14
4      1  San Zhang         Mid     Math     85    20
5      1  San Zhang       Final     Math     75     7
6      2      Si Li         Mid     Math     60     6
7      2      Si Li       Final     Math     88     3
                  Grade                     rank                 
Sub

#### 索引的变形

In [20]:

import numpy as np
import pandas as pd
# stack与unstack方法, 用于行列索引之间的交换
print('stack与unstack方法')
df = pd.DataFrame(np.ones((4,2)),index=pd.Index([('A', 'cat', 'big'),('A', 'dog', 'small'),('B', 'cat', 'big'),('B', 'dog', 'small')]), columns=['col_1', 'col_2'])
print(df)
print(df.unstack()) # 把行索引转为列索引, 要求被转为列索引的行索引 和 被保留的行索引层构成的组合必须是唯一的
print(df.unstack([0,1])) # 转化多个层
df = pd.DataFrame(np.ones((4,2)),index=pd.Index([('A', 'cat', 'big'),('A', 'dog', 'small'),('B', 'cat', 'big'),('B', 'dog', 'small')]), columns=['index_1', 'index_2']).T
print(df)
print(df.stack()) # 将列索引层压入行索引
print(df.stack([1,2])) # 转化多个层

stack与unstack方法
             col_1  col_2
A cat big      1.0    1.0
  dog small    1.0    1.0
B cat big      1.0    1.0
  dog small    1.0    1.0
      col_1       col_2      
        big small   big small
A cat   1.0   NaN   1.0   NaN
  dog   NaN   1.0   NaN   1.0
B cat   1.0   NaN   1.0   NaN
  dog   NaN   1.0   NaN   1.0
      col_1                col_2               
          A         B          A         B     
        cat  dog  cat  dog   cat  dog  cat  dog
big     1.0  NaN  1.0  NaN   1.0  NaN  1.0  NaN
small   NaN  1.0  NaN  1.0   NaN  1.0  NaN  1.0
           A          B      
         cat   dog  cat   dog
         big small  big small
index_1  1.0   1.0  1.0   1.0
index_2  1.0   1.0  1.0   1.0
                 A         B     
               cat  dog  cat  dog
index_1 big    1.0  NaN  1.0  NaN
        small  NaN  1.0  NaN  1.0
index_2 big    1.0  NaN  1.0  NaN
        small  NaN  1.0  NaN  1.0
                     A    B
index_1 cat big    1.0  1.0
        dog small  1.0  

#### 其他变形函数

In [28]:
import numpy as np
import pandas as pd
# crosstab方法, 用于计算分组频率的特殊透视表
df = pd.read_csv('../data/learn_pandas.csv')
print(pd.crosstab(index=df.School, columns=df.Transfer))
print(df.pivot_table(index='School', columns='Transfer', aggfunc='count', values='Name')) # 等价写法(pivot_table方法)
print(pd.crosstab(index=df.School, columns=df.Transfer, values=df.Height, aggfunc='mean')) # 传入values参数, 计算身高均值

# explode方法, 对某一列函数纵向展开
df_test = pd.DataFrame({'A':[[1,2], 'my_str', {1,2}, pd.Series([3,4])], 'B':1})
print(df_test)
print(df_test.explode('A'))

# get_dummies方法, 把类别特征转为指示变量
print(pd.get_dummies(df.Grade).head()) # 得到指示变量的DataFrame

Transfer                        N  Y
School                              
Fudan University               38  1
Peking University              28  2
Shanghai Jiao Tong University  53  0
Tsinghua University            62  4
Transfer                          N    Y
School                                  
Fudan University               38.0  1.0
Peking University              28.0  2.0
Shanghai Jiao Tong University  53.0  NaN
Tsinghua University            62.0  4.0
Transfer                                N       Y
School                                           
Fudan University               162.043750  177.20
Peking University              163.429630  162.40
Shanghai Jiao Tong University  163.953846     NaN
Tsinghua University            163.253571  164.55
                            A  B
0                      [1, 2]  1
1                      my_str  1
2                      {1, 2}  1
3  0    3
1    4
dtype: int64  1
        A  B
0       1  1
0       2  1
1  my_str  1
2       1  1
2 

# 连接

#### 关系型连接

In [14]:
import numpy as np
import pandas as pd
# 值连接
print('值连接')
df1 = pd.DataFrame({'Name': ['San Zhang', 'Si Li'], 'Age': [20, 21]})
df2 = pd.DataFrame({'Name': ['Wu Wang', 'Si Li'], 'Gender': ['M', 'F']})
# merge方法, on参数表示连接的列, how参数表示连接方式, left表示左连接, right表示右连接, inner表示内连接, outer表示外连接
print(df1.merge(df2, on='Name', how='left')) 
print(df1.merge(df2, on='Name', how='right'))
print(df1.merge(df2, on='Name', how='inner'))
print(df1.merge(df2, on='Name', how='outer'))
df1 = pd.DataFrame({'df1_name': ['San Zhang', 'Si Li'], 'Age': [20, 21]})
df2 = pd.DataFrame({'df2_name': ['Wu Wang', 'Si Li'], 'Gender': ['M', 'F']})
print(df1.merge(df2, left_on='df1_name', right_on='df2_name', how='left')) # 连接的列不具备相同的列名
df1 = pd.DataFrame({'Name':['Lily'], 'Grade':[80]})
df2 = pd.DataFrame({'Name':['Lily'], 'Grade':[90]})
print(df1.merge(df2, on='Name', how='left', suffixes=['_English', '_Math'])) # suffixes参数表示连接的列名相同时的后缀
df1 = pd.DataFrame({'Name':['San Zhang', 'San Zhang'], 'Age':[20, 21], 'Class':['one', 'two']})
df2 = pd.DataFrame({'Name':['San Zhang', 'San Zhang'], 'Gender':['F', 'M'], 'Class':['two', 'one']})
print(df1)
print(df2)
print('Wrong Answer')
print(df1.merge(df2, on='Name', how='left')) # 返回笛卡尔积
print('Right Answer')
print(df1.merge(df2, on=['Name', 'Class'], how='left')) # 多列连接, 返回正确结果

# 索引连接
print('索引连接')
df1 = pd.DataFrame({'Age': [20, 21]}, index=pd.Index(['San Zhang', 'Si Li'], name='Name'))
df2 = pd.DataFrame({'Gender': ['M', 'F']}, index=pd.Index(['Wu Wang', 'Si Li'], name='Name'))
print(df1.join(df2, how='left'))
df1 = pd.DataFrame({'Grade':[70]}, index=pd.Series(['San Zhang'], name='Name'))
df2 = pd.DataFrame({'Grade':[80]}, index=pd.Series(['San Zhang'], name='Name'))
print(df1.join(df2, lsuffix='_Chinese', rsuffix='_Math')) # suffixes参数表示连接的列名相同时的后缀
# 以多列为键操作, 需要多级索引
df1 = pd.DataFrame({'Age':[20, 21]}, index=pd.MultiIndex.from_arrays([['San Zhang', 'San Zhang'], ['one', 'two']], names=('Name', 'Class')))
df2 = pd.DataFrame({'Gender':['F', 'M']}, index=pd.MultiIndex.from_arrays([['San Zhang', 'San Zhang'], ['two', 'one']], names=('Name', 'Class')))
print(df1.join(df2))

值连接
        Name  Age Gender
0  San Zhang   20    NaN
1      Si Li   21      F
      Name   Age Gender
0  Wu Wang   NaN      M
1    Si Li  21.0      F
    Name  Age Gender
0  Si Li   21      F
        Name   Age Gender
0  San Zhang  20.0    NaN
1      Si Li  21.0      F
2    Wu Wang   NaN      M
    df1_name  Age df2_name Gender
0  San Zhang   20      NaN    NaN
1      Si Li   21    Si Li      F
   Name  Grade_English  Grade_Math
0  Lily             80          90
        Name  Age Class
0  San Zhang   20   one
1  San Zhang   21   two
        Name Gender Class
0  San Zhang      F   two
1  San Zhang      M   one
Wrong Answer
        Name  Age Class_x Gender Class_y
0  San Zhang   20     one      F     two
1  San Zhang   20     one      M     one
2  San Zhang   21     two      F     two
3  San Zhang   21     two      M     one
Right Answer
        Name  Age Class Gender
0  San Zhang   20   one      M
1  San Zhang   21   two      F
索引连接
           Age Gender
Name                 
San Zhan

#### 方向连接

In [29]:
import numpy as np
import pandas as pd
# concat方法, 用于连接多个DataFrame, axis参数表示连接的方向, join参数表示连接的方式, keys参数表示在新表中指示来自哪张旧表的名字
print('concat方法')
df1 = pd.DataFrame({'Name': ['San Zhang', 'Si Li'], 'Age': [20, 21]})
df2 = pd.DataFrame({'Name': ['Wu Wang'], 'Age': [30]})
print(pd.concat([df1, df2]))
df2 = pd.DataFrame({'Grade': [80, 90]})
df3 = pd.DataFrame({'Gender': ['M', 'F']})
print(pd.concat([df1, df2, df3], axis=1))
df2 = pd.DataFrame({'Grade': [80, 90]}, index=[1, 2])
# join参数表示连接的方式, inner表示保留两个表都出现过的列, outer表示保留所有列并把不存在的值设为缺失
print(pd.concat([df1, df2], axis=1, join='outer'))
print(pd.concat([df1, df2], axis=1, join='inner')) # join参数表示连接的方式, inner表示内连接, outer表示外连接
df1 = pd.DataFrame({'Name': ['San Zhang', 'Si Li'], 'Age': [20, 21]})
df2 = pd.DataFrame({'Name': ['Wu Wang'], 'Age': [30]})
print(pd.concat([df1, df2], keys=['class_one', 'class_two']))

# 序列与表的合并
print('序列与表的合并')
# assign方法
series = pd.Series([80, 90])
print(df1.assign(grade=series)) # 返回的是临时表, 不会改变原表
print(df1)

concat方法
        Name  Age
0  San Zhang   20
1      Si Li   21
0    Wu Wang   30
        Name  Age  Grade Gender
0  San Zhang   20     80      M
1      Si Li   21     90      F
        Name   Age  Grade
0  San Zhang  20.0    NaN
1      Si Li  21.0   80.0
2        NaN   NaN   90.0
    Name  Age  Grade
1  Si Li   21     80
                  Name  Age
class_one 0  San Zhang   20
          1      Si Li   21
class_two 0    Wu Wang   30
序列与表的合并
        Name  Age  grade
0  San Zhang   20     80
1      Si Li   21     90
        Name  Age
0  San Zhang   20
1      Si Li   21


#### 类连接操作

In [35]:
import numpy as np
import pandas as pd
# 比较
df1 = pd.DataFrame({'Name': ['San Zhang', 'Si Li'], 'Age': [20, 21]})
df2 = pd.DataFrame({'Name': ['Wu Wang', 'Si Li'], 'Age': [22, 21]})
print(df1.compare(df2, keep_shape=True)) # 相同值用NaN填充, keep_shape参数表示保持原表的形状

# 组合
print(df1.combine(df2, np.fmax)) 

        Name            Age      
        self    other  self other
0  San Zhang  Wu Wang  20.0  22.0
1        NaN      NaN   NaN   NaN
      Name  Age
0  Wu Wang   22
1    Si Li   21


# 缺失数据

#### 缺失值的统计和删除

In [18]:
import numpy as np
import pandas as pd
# 缺失信息的统计
print('缺失信息的统计')
df = pd.read_csv('../data/learn_pandas.csv', usecols=['Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer'])
print(df.isna().head()) # isna方法, 与isnull方法等价
print(df.isna().mean()) # mean方法返回每一列缺失值的比例
print(df[df.Height.isna()].head()) # 用Series上的isna方法布尔索引找到某一列的缺失, 这里找的是身高缺失的行
df_tmp = df[['Height', 'Weight', 'Transfer']]
print(df[df_tmp.isna().all(1)].head()) # isna结合all判断是否全部缺失
print(df[df_tmp.isna().any(axis=1)].head()) # isna结合any判断是否至少有一个缺失, axis=1不可以缺失否则报错TypeError: DataFrame.any() takes 1 positional argument but 2 were given
print(df[df_tmp.notna().all(1)].head()) # notna结合all判断是否没有缺失

# 缺失信息的删除
print('缺失信息的删除')
print(df.shape)
print(df.dropna(how='any', subset=['Height', 'Weight']).shape) # dropna方法, how参数表示删除的方式, subset参数表示删除的列
print(df.dropna(axis=1, thresh=df.shape[0]-15).head()) # thresh表示删除的非缺失值个数阈值, 非缺失值个数小于阈值的列会被删除
print(df.dropna(axis=1, thresh=df.shape[0]-15).shape)

缺失信息的统计
   Grade   Name  Gender  Height  Weight  Transfer
0  False  False   False   False   False     False
1  False  False   False   False   False     False
2  False  False   False   False   False     False
3  False  False   False    True   False     False
4  False  False   False   False   False     False
Grade       0.000
Name        0.000
Gender      0.000
Height      0.085
Weight      0.055
Transfer    0.060
dtype: float64
        Grade          Name  Gender  Height  Weight Transfer
3   Sophomore  Xiaojuan Sun  Female     NaN    41.0        N
12     Senior      Peng You  Female     NaN    48.0      NaN
26     Junior     Yanli You  Female     NaN    48.0        N
36   Freshman  Xiaojuan Qin    Male     NaN    79.0        Y
60   Freshman    Yanpeng Lv    Male     NaN    65.0        N
      Grade          Name Gender  Height  Weight Transfer
102  Junior  Chengli Zhao   Male     NaN     NaN      NaN
        Grade           Name  Gender  Height  Weight Transfer
3   Sophomore   Xiaojuan 

#### 缺失值的填充和插值


In [29]:
import numpy as np
import pandas as pd
# 利用fillna方法填充缺失值
print('利用fillna方法填充缺失值')
series = pd.Series([np.nan, 1, np.nan, np.nan, 3], index=list('abaae'))
print(series)
print(series.fillna(method='ffill')) # ffill表示用前一个非缺失值向后填充
print(series.fillna(method='ffill', limit=1)) # limit参数表示最多填充的个数, 连续的缺失值只填充一个
print(series.fillna(value=series.mean())) # value参数表示填充的值
print(series.fillna({'a': 10})) # 传入字典, 指定填充的值

# 插值函数
print('插值函数')
series = pd.Series([np.nan, np.nan, 1, np.nan, np.nan, np.nan, 2, np.nan, np.nan])
print(series.values)
# 线性插值
print(series.interpolate(limit_direction='backward', limit=1).values) # limit_direction参数表示插值的方向, limit参数表示最多插值的个数, 默认线性插值
print(series.interpolate(limit_direction='both', limit=1).values)
# 最近邻插值, 注意这里要装scipy包
print(series.interpolate(method='nearest').values)
# 索引插值
series = pd.Series([0, np.nan, 100], index=[0, 1, 10])
print(series)
print(series.interpolate()) # 默认线性插值
print(series.interpolate(method='index')) # 索引插值, 计算相应索引大小对应的值
series = pd.Series([0, np.nan, 100], index=[pd.Timestamp('20200101'), pd.Timestamp('20200102'), pd.Timestamp('20200111')])
print(series)
print(series.interpolate()) # 默认线性插值
print(series.interpolate(method='index')) # 对时间戳索引进行索引插值, 计算相应索引大小对应的值

利用fillna方法填充缺失值
a    NaN
b    1.0
a    NaN
a    NaN
e    3.0
dtype: float64
a    NaN
b    1.0
a    1.0
a    1.0
e    3.0
dtype: float64
a    NaN
b    1.0
a    1.0
a    NaN
e    3.0
dtype: float64
a    2.0
b    1.0
a    2.0
a    2.0
e    3.0
dtype: float64
a    10.0
b     1.0
a    10.0
a    10.0
e     3.0
dtype: float64
插值函数
[nan nan  1. nan nan nan  2. nan nan]
[ nan 1.   1.    nan  nan 1.75 2.    nan  nan]
[ nan 1.   1.   1.25  nan 1.75 2.   2.    nan]
[nan nan  1.  1.  1.  2.  2. nan nan]
0       0.0
1       NaN
10    100.0
dtype: float64
0       0.0
1      50.0
10    100.0
dtype: float64
0       0.0
1      10.0
10    100.0
dtype: float64
2020-01-01      0.0
2020-01-02      NaN
2020-01-11    100.0
dtype: float64
2020-01-01      0.0
2020-01-02     50.0
2020-01-11    100.0
dtype: float64
2020-01-01      0.0
2020-01-02     10.0
2020-01-11    100.0
dtype: float64


C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_6840\3776894981.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(series.fillna(method='ffill')) # ffill表示用前一个非缺失值向后填充
C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_6840\3776894981.py:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(series.fillna(method='ffill', limit=1)) # limit参数表示最多填充的个数, 连续的缺失值只填充一个


#### Nullable类型

In [47]:
import numpy as np
import pandas as pd
# 缺失记号及其缺陷
print('缺失记号及其缺陷')
print(None==None, None==[], None==False) # None只与自身相等
print(np.nan==np.nan, np.nan==[], np.nan==False) # np.nan与任何对象都不相等
s1 = pd.Series([1, np.nan])
s2 = pd.Series([1, 2])
s3 = pd.Series([1, np.nan])
print(s1.equals(s2), s1.equals(s3)) # equals方法, 比较两个Series是否相等, 这里直接跳过了np.nan的比较
print(pd.to_datetime(['20231124', np.nan])) # 时间序列用pd.NaT表示时间戳的缺失值

# Nullable类型的性质
print('Nullable类型的性质')
print(pd.Series([1, np.nan], dtype='Int64'))
print(pd.Series([True, np.nan], dtype='boolean'))
print(pd.Series([1, np.nan], dtype='Int64') + 1)
print(pd.Series([1, np.nan], dtype='Int64') == 1)
print(pd.Series([1, np.nan], dtype='Int64') + 0.5)
s = pd.Series(['a', 'b'])
print(s[pd.Series([True, np.nan]).astype('boolean')]) # astype方法, 转换类型为boolean, 这里把np.nan转换为了False
print(pd.Series([True, np.nan]).astype('boolean') & True) # boolean类型会根据逻辑运算是否能确定唯一结果来返回相应的值
df = pd.read_csv('../data/learn_pandas.csv')
df = df.convert_dtypes() # convert_dtypes方法, 将DataFrame中的列转换为Nullable类型
print(df.dtypes)

# 缺失数据的计算和分组
print('缺失数据的计算和分组')
s = pd.Series([1, np.nan, 2, 4, 3])
print(s.sum()) # 加法np.nan当作0
print(s.prod()) # 乘法np.nan当作1
print(s.cumsum()) # 累加np.nan被跳过

缺失记号及其缺陷
True False False
False False False
False True
DatetimeIndex(['2023-11-24', 'NaT'], dtype='datetime64[ns]', freq=None)
Nullable类型的性质
0       1
1    <NA>
dtype: Int64
0    True
1    <NA>
dtype: boolean
0       2
1    <NA>
dtype: Int64
0    True
1    <NA>
dtype: boolean
0     1.5
1    <NA>
dtype: Float64
0    a
dtype: object
0    True
1    <NA>
dtype: boolean
School         string[python]
Grade          string[python]
Name           string[python]
Gender         string[python]
Height                Float64
Weight                  Int64
Transfer       string[python]
Test_Number             Int64
Test_Date      string[python]
Time_Record    string[python]
dtype: object
缺失数据的计算和分组
10.0
24.0
0     1.0
1     NaN
2     3.0
3     7.0
4    10.0
dtype: float64
